task: "qd"

qd:
  n: 10
  p: 0.1
  sigma: 0.01
  generation: 10 # how many generations do we run?
  proportion: 0.2 # top we keep?
  dimensions: 2000
  population: 100
  rep: "turtle"
  game: "smb"

mcts:
  game: "tic_tac_toe"
  maxim: "human"
  minim: "monte_carlo"
  compute: 100000
  c: 0.9

ann:
  hidden: 30
  epochs: 1000
  silas: 0.00001
  lr: 0.001
